### ISSUE TITLE
Please update it!

### ISSUE THREAD

**Issue by philipperemy** [suguru03/made-in-japan#2]
Thanks!

**Comment by suguru03** [comment]
Sure.
I'm thinking to make it automatically, but I don't have time to spend it.
I'll do it soon, thanks!

**Comment by philipperemy** [comment]
If there's anything I can do, let me know!
It should not be too hard to automate it.
Thanks for the quick feedback!

**Comment by suguru03** [comment]
Thanks! 
I'll look into it this week. :)

**Comment by philipperemy** [comment]
Thanks! Let me know how I can help if you need :)

**Comment by suguru03** [comment]
I refactored and updated. The tasks are very faster than before. ;)
We could use circle ci to automate it. 
https://circleci.com/docs/1.0/nightly-builds/

**Comment by philipperemy** [comment]
@suguru03 seems great! ;)

Just one thing I wanted to point out is the calculation of the number of stars.

https://gist.github.com/yyx990803/7745157

I found this gist and when I run it on my user, I get a slightly different result from yours:

```
[10:42:33 - 17-05-22] /tmp % node count_stars.js philipperemy -t 9

Total: 423

Reuters-full-data-set                 ★  51
tensorflow-phased-lstm                ★  46
Deep-Learning-Tinder                  ★  45
Stanford-OpenIE-Python                ★  36
Order-Book-Matching-Engine            ★  28
financial-news-dataset                ★  20
yolo-9000                             ★  17
tensorflow-maxout                     ★  15
Market-Data                           ★  12
wavenet                               ★  11
tensorflow-class-activation-mapping   ★  9
```

Yours is 390. What do you use? Maybe this script I found is not correct!

**Comment by suguru03** [comment]
🤔
The total seems to include all repo's stars.
```
node count_stars.js philipperemy -t 30

Tatal: 423

Reuters-full-data-set    ★  51
tensorflow-phased-lstm   ★  46
Deep-Learning-Tinder     ★  45
Stanford-OpenIE-Python   ★  36
```
The total should be 178.
https://gist.github.com/suguru03/8859bdfd2f74d2adee39235eade681b5#file-starcounter-js-L45-L47

The repo's threshold is 3. 
https://github.com/suguru03/made-in-generator/blob/master/lib/madeIn.js#L191

I want to avoid self counting, I think 3 is fine.

**Comment by philipperemy** [comment]
@suguru03 seems good for me!! Thanks a lot ;)
